local tween = require('tween')

describe('tween', function()

  describe('tween.start', function()
    test('time should be a positive number', function()
      assert_error(function() tween.start(0, {}, {}) end)
      assert_error(function() tween.start(-1, {}, {}) end)
      assert_error(function() tween.start('foo', {}, {}) end)
      assert_not_error(function() tween.start(1, {}, {}) end)
    end)

    test('subject should be a table', function()
      assert_error(function() tween.start(1, 1, {}) end)
      assert_error(function() tween.start(1, "foo", {}) end)
      assert_not_error(function() tween.start(1, {}, {}) end)
    end)

    test('target should be a table', function()
      assert_error(function() tween.start(1, {}, 1) end)
      assert_error(function() tween.start(1, {}, "foo") end)
      assert_not_error(function() tween.start(1, {}, {}) end)
    end)

    test('target data can only be numbers', function()
      assert_error(function() tween.start(1, {1,2}, {'a', 'b'}) end)
      assert_error(function() tween.start(1, {x=1}, {x = print}) end)
      assert_not_error(function() tween.start(1, {x=1}, {x = 2}) end)
    end)

    test('subject data with a target must be a number', function()
      assert_error(function() tween.start(1, {}, {x=1}) end)
      assert_error(function() tween.start(1, {y=1}, {x = 1}) end)
    end)

    test('easing must be a function or valid easing function name, or nil', function()
      assert_error(function() tween.start(1, {}, {}, 'foo') end)
      assert_not_error(function() tween.start(1, {}, {}, function() end) end)
      assert_not_error(function() tween.start(1, {}, {}, 'linear') end)
    end)
  end)
end)
